name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:
  
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Check current directory
      run: echo %cd%
    
    
    - name: Check Requirements
      run: pip install -r requirements.txt
    
    
    - name: Execute bot
      run: python bot.py

